ARG UBI_VERSION=9
ARG PYTHON_VERSION=311

FROM registry.access.redhat.com/ubi${UBI_VERSION}/python-${PYTHON_VERSION}:latest

ARG PIP_INDEX_URL=https://pypi.org/simple/
ARG PIP_TRUSTED_HOST=pypi.org

USER 0

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir \
    --index-url ${PIP_INDEX_URL} \
    --trusted-host ${PIP_TRUSTED_HOST} \
    -r requirements.txt

COPY test_analyzer.py .

RUN mkdir -p /test-certs && \
    chown -R 1001:0 /app /test-certs && \
    chmod -R g=u /app /test-certs

USER 1001

VOLUME ["/test-certs"]

ENV TEST_CERT_OUTPUT_DIR=/test-certs

ENTRYPOINT ["python", "-u", "test_analyzer.py"]
