ARG UBI_VERSION=9
ARG PYTHON_VERSION=311

FROM registry.access.redhat.com/ubi${UBI_VERSION}/python-${PYTHON_VERSION}:latest

ARG PIP_INDEX_URL=https://pypi.org/simple/
ARG PIP_TRUSTED_HOST=pypi.org

USER 0

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir \
    --index-url ${PIP_INDEX_URL} \
    --trusted-host ${PIP_TRUSTED_HOST} \
    -r requirements.txt

COPY soak_test.py .

ENTRYPOINT ["python3", "-u", "soak_test.py"]
