[Service]
ExecStart=
ExecStart=/usr/local/bin/tetragon \
  --export-filename /var/log/tetragon/tetragon.log \
  --server-address unix:///var/run/tetragon/tetragon.sock \
  --procfs /proc
ExecStartPost=/bin/chgrp cert-analyzer /var/run/tetragon/tetragon.sock
