from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class BpfCmd(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    BPF_MAP_CREATE: _ClassVar[BpfCmd]
    BPF_MAP_LOOKUP_ELEM: _ClassVar[BpfCmd]
    BPF_MAP_UPDATE_ELEM: _ClassVar[BpfCmd]
    BPF_MAP_DELETE_ELEM: _ClassVar[BpfCmd]
    BPF_MAP_GET_NEXT_KEY: _ClassVar[BpfCmd]
    BPF_PROG_LOAD: _ClassVar[BpfCmd]
    BPF_OBJ_PIN: _ClassVar[BpfCmd]
    BPF_OBJ_GET: _ClassVar[BpfCmd]
    BPF_PROG_ATTACH: _ClassVar[BpfCmd]
    BPF_PROG_DETACH: _ClassVar[BpfCmd]
    BPF_PROG_TEST_RUN: _ClassVar[BpfCmd]
    BPF_PROG_GET_NEXT_ID: _ClassVar[BpfCmd]
    BPF_MAP_GET_NEXT_ID: _ClassVar[BpfCmd]
    BPF_PROG_GET_FD_BY_ID: _ClassVar[BpfCmd]
    BPF_MAP_GET_FD_BY_ID: _ClassVar[BpfCmd]
    BPF_OBJ_GET_INFO_BY_FD: _ClassVar[BpfCmd]
    BPF_PROG_QUERY: _ClassVar[BpfCmd]
    BPF_RAW_TRACEPOINT_OPEN: _ClassVar[BpfCmd]
    BPF_BTF_LOAD: _ClassVar[BpfCmd]
    BPF_BTF_GET_FD_BY_ID: _ClassVar[BpfCmd]
    BPF_TASK_FD_QUERY: _ClassVar[BpfCmd]
    BPF_MAP_LOOKUP_AND_DELETE_ELEM: _ClassVar[BpfCmd]
    BPF_MAP_FREEZE: _ClassVar[BpfCmd]
    BPF_BTF_GET_NEXT_ID: _ClassVar[BpfCmd]
    BPF_MAP_LOOKUP_BATCH: _ClassVar[BpfCmd]
    BPF_MAP_LOOKUP_AND_DELETE_BATCH: _ClassVar[BpfCmd]
    BPF_MAP_UPDATE_BATCH: _ClassVar[BpfCmd]
    BPF_MAP_DELETE_BATCH: _ClassVar[BpfCmd]
    BPF_LINK_CREATE: _ClassVar[BpfCmd]
    BPF_LINK_UPDATE: _ClassVar[BpfCmd]
    BPF_LINK_GET_FD_BY_ID: _ClassVar[BpfCmd]
    BPF_LINK_GET_NEXT_ID: _ClassVar[BpfCmd]
    BPF_ENABLE_STATS: _ClassVar[BpfCmd]
    BPF_ITER_CREATE: _ClassVar[BpfCmd]
    BPF_LINK_DETACH: _ClassVar[BpfCmd]
    BPF_PROG_BIND_MAP: _ClassVar[BpfCmd]
    BPF_TOKEN_CREATE: _ClassVar[BpfCmd]

class BpfProgramType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    BPF_PROG_TYPE_UNSPEC: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SOCKET_FILTER: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_KPROBE: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SCHED_CLS: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SCHED_ACT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_TRACEPOINT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_XDP: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_PERF_EVENT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_CGROUP_SKB: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_CGROUP_SOCK: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_LWT_IN: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_LWT_OUT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_LWT_XMIT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SOCK_OPS: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SK_SKB: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_CGROUP_DEVICE: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SK_MSG: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_RAW_TRACEPOINT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_CGROUP_SOCK_ADDR: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_LWT_SEG6LOCAL: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_LIRC_MODE2: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SK_REUSEPORT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_FLOW_DISSECTOR: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_CGROUP_SYSCTL: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_CGROUP_SOCKOPT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_TRACING: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_STRUCT_OPS: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_EXT: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_LSM: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SK_LOOKUP: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_SYSCALL: _ClassVar[BpfProgramType]
    BPF_PROG_TYPE_NETFILTER: _ClassVar[BpfProgramType]
BPF_MAP_CREATE: BpfCmd
BPF_MAP_LOOKUP_ELEM: BpfCmd
BPF_MAP_UPDATE_ELEM: BpfCmd
BPF_MAP_DELETE_ELEM: BpfCmd
BPF_MAP_GET_NEXT_KEY: BpfCmd
BPF_PROG_LOAD: BpfCmd
BPF_OBJ_PIN: BpfCmd
BPF_OBJ_GET: BpfCmd
BPF_PROG_ATTACH: BpfCmd
BPF_PROG_DETACH: BpfCmd
BPF_PROG_TEST_RUN: BpfCmd
BPF_PROG_GET_NEXT_ID: BpfCmd
BPF_MAP_GET_NEXT_ID: BpfCmd
BPF_PROG_GET_FD_BY_ID: BpfCmd
BPF_MAP_GET_FD_BY_ID: BpfCmd
BPF_OBJ_GET_INFO_BY_FD: BpfCmd
BPF_PROG_QUERY: BpfCmd
BPF_RAW_TRACEPOINT_OPEN: BpfCmd
BPF_BTF_LOAD: BpfCmd
BPF_BTF_GET_FD_BY_ID: BpfCmd
BPF_TASK_FD_QUERY: BpfCmd
BPF_MAP_LOOKUP_AND_DELETE_ELEM: BpfCmd
BPF_MAP_FREEZE: BpfCmd
BPF_BTF_GET_NEXT_ID: BpfCmd
BPF_MAP_LOOKUP_BATCH: BpfCmd
BPF_MAP_LOOKUP_AND_DELETE_BATCH: BpfCmd
BPF_MAP_UPDATE_BATCH: BpfCmd
BPF_MAP_DELETE_BATCH: BpfCmd
BPF_LINK_CREATE: BpfCmd
BPF_LINK_UPDATE: BpfCmd
BPF_LINK_GET_FD_BY_ID: BpfCmd
BPF_LINK_GET_NEXT_ID: BpfCmd
BPF_ENABLE_STATS: BpfCmd
BPF_ITER_CREATE: BpfCmd
BPF_LINK_DETACH: BpfCmd
BPF_PROG_BIND_MAP: BpfCmd
BPF_TOKEN_CREATE: BpfCmd
BPF_PROG_TYPE_UNSPEC: BpfProgramType
BPF_PROG_TYPE_SOCKET_FILTER: BpfProgramType
BPF_PROG_TYPE_KPROBE: BpfProgramType
BPF_PROG_TYPE_SCHED_CLS: BpfProgramType
BPF_PROG_TYPE_SCHED_ACT: BpfProgramType
BPF_PROG_TYPE_TRACEPOINT: BpfProgramType
BPF_PROG_TYPE_XDP: BpfProgramType
BPF_PROG_TYPE_PERF_EVENT: BpfProgramType
BPF_PROG_TYPE_CGROUP_SKB: BpfProgramType
BPF_PROG_TYPE_CGROUP_SOCK: BpfProgramType
BPF_PROG_TYPE_LWT_IN: BpfProgramType
BPF_PROG_TYPE_LWT_OUT: BpfProgramType
BPF_PROG_TYPE_LWT_XMIT: BpfProgramType
BPF_PROG_TYPE_SOCK_OPS: BpfProgramType
BPF_PROG_TYPE_SK_SKB: BpfProgramType
BPF_PROG_TYPE_CGROUP_DEVICE: BpfProgramType
BPF_PROG_TYPE_SK_MSG: BpfProgramType
BPF_PROG_TYPE_RAW_TRACEPOINT: BpfProgramType
BPF_PROG_TYPE_CGROUP_SOCK_ADDR: BpfProgramType
BPF_PROG_TYPE_LWT_SEG6LOCAL: BpfProgramType
BPF_PROG_TYPE_LIRC_MODE2: BpfProgramType
BPF_PROG_TYPE_SK_REUSEPORT: BpfProgramType
BPF_PROG_TYPE_FLOW_DISSECTOR: BpfProgramType
BPF_PROG_TYPE_CGROUP_SYSCTL: BpfProgramType
BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE: BpfProgramType
BPF_PROG_TYPE_CGROUP_SOCKOPT: BpfProgramType
BPF_PROG_TYPE_TRACING: BpfProgramType
BPF_PROG_TYPE_STRUCT_OPS: BpfProgramType
BPF_PROG_TYPE_EXT: BpfProgramType
BPF_PROG_TYPE_LSM: BpfProgramType
BPF_PROG_TYPE_SK_LOOKUP: BpfProgramType
BPF_PROG_TYPE_SYSCALL: BpfProgramType
BPF_PROG_TYPE_NETFILTER: BpfProgramType
