from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CapabilitiesType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CAP_CHOWN: _ClassVar[CapabilitiesType]
    DAC_OVERRIDE: _ClassVar[CapabilitiesType]
    CAP_DAC_READ_SEARCH: _ClassVar[CapabilitiesType]
    CAP_FOWNER: _ClassVar[CapabilitiesType]
    CAP_FSETID: _ClassVar[CapabilitiesType]
    CAP_KILL: _ClassVar[CapabilitiesType]
    CAP_SETGID: _ClassVar[CapabilitiesType]
    CAP_SETUID: _ClassVar[CapabilitiesType]
    CAP_SETPCAP: _ClassVar[CapabilitiesType]
    CAP_LINUX_IMMUTABLE: _ClassVar[CapabilitiesType]
    CAP_NET_BIND_SERVICE: _ClassVar[CapabilitiesType]
    CAP_NET_BROADCAST: _ClassVar[CapabilitiesType]
    CAP_NET_ADMIN: _ClassVar[CapabilitiesType]
    CAP_NET_RAW: _ClassVar[CapabilitiesType]
    CAP_IPC_LOCK: _ClassVar[CapabilitiesType]
    CAP_IPC_OWNER: _ClassVar[CapabilitiesType]
    CAP_SYS_MODULE: _ClassVar[CapabilitiesType]
    CAP_SYS_RAWIO: _ClassVar[CapabilitiesType]
    CAP_SYS_CHROOT: _ClassVar[CapabilitiesType]
    CAP_SYS_PTRACE: _ClassVar[CapabilitiesType]
    CAP_SYS_PACCT: _ClassVar[CapabilitiesType]
    CAP_SYS_ADMIN: _ClassVar[CapabilitiesType]
    CAP_SYS_BOOT: _ClassVar[CapabilitiesType]
    CAP_SYS_NICE: _ClassVar[CapabilitiesType]
    CAP_SYS_RESOURCE: _ClassVar[CapabilitiesType]
    CAP_SYS_TIME: _ClassVar[CapabilitiesType]
    CAP_SYS_TTY_CONFIG: _ClassVar[CapabilitiesType]
    CAP_MKNOD: _ClassVar[CapabilitiesType]
    CAP_LEASE: _ClassVar[CapabilitiesType]
    CAP_AUDIT_WRITE: _ClassVar[CapabilitiesType]
    CAP_AUDIT_CONTROL: _ClassVar[CapabilitiesType]
    CAP_SETFCAP: _ClassVar[CapabilitiesType]
    CAP_MAC_OVERRIDE: _ClassVar[CapabilitiesType]
    CAP_MAC_ADMIN: _ClassVar[CapabilitiesType]
    CAP_SYSLOG: _ClassVar[CapabilitiesType]
    CAP_WAKE_ALARM: _ClassVar[CapabilitiesType]
    CAP_BLOCK_SUSPEND: _ClassVar[CapabilitiesType]
    CAP_AUDIT_READ: _ClassVar[CapabilitiesType]
    CAP_PERFMON: _ClassVar[CapabilitiesType]
    CAP_BPF: _ClassVar[CapabilitiesType]
    CAP_CHECKPOINT_RESTORE: _ClassVar[CapabilitiesType]

class SecureBitsType(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SecBitNotSet: _ClassVar[SecureBitsType]
    SecBitNoRoot: _ClassVar[SecureBitsType]
    SecBitNoRootLocked: _ClassVar[SecureBitsType]
    SecBitNoSetUidFixup: _ClassVar[SecureBitsType]
    SecBitNoSetUidFixupLocked: _ClassVar[SecureBitsType]
    SecBitKeepCaps: _ClassVar[SecureBitsType]
    SecBitKeepCapsLocked: _ClassVar[SecureBitsType]
    SecBitNoCapAmbientRaise: _ClassVar[SecureBitsType]
    SecBitNoCapAmbientRaiseLocked: _ClassVar[SecureBitsType]
CAP_CHOWN: CapabilitiesType
DAC_OVERRIDE: CapabilitiesType
CAP_DAC_READ_SEARCH: CapabilitiesType
CAP_FOWNER: CapabilitiesType
CAP_FSETID: CapabilitiesType
CAP_KILL: CapabilitiesType
CAP_SETGID: CapabilitiesType
CAP_SETUID: CapabilitiesType
CAP_SETPCAP: CapabilitiesType
CAP_LINUX_IMMUTABLE: CapabilitiesType
CAP_NET_BIND_SERVICE: CapabilitiesType
CAP_NET_BROADCAST: CapabilitiesType
CAP_NET_ADMIN: CapabilitiesType
CAP_NET_RAW: CapabilitiesType
CAP_IPC_LOCK: CapabilitiesType
CAP_IPC_OWNER: CapabilitiesType
CAP_SYS_MODULE: CapabilitiesType
CAP_SYS_RAWIO: CapabilitiesType
CAP_SYS_CHROOT: CapabilitiesType
CAP_SYS_PTRACE: CapabilitiesType
CAP_SYS_PACCT: CapabilitiesType
CAP_SYS_ADMIN: CapabilitiesType
CAP_SYS_BOOT: CapabilitiesType
CAP_SYS_NICE: CapabilitiesType
CAP_SYS_RESOURCE: CapabilitiesType
CAP_SYS_TIME: CapabilitiesType
CAP_SYS_TTY_CONFIG: CapabilitiesType
CAP_MKNOD: CapabilitiesType
CAP_LEASE: CapabilitiesType
CAP_AUDIT_WRITE: CapabilitiesType
CAP_AUDIT_CONTROL: CapabilitiesType
CAP_SETFCAP: CapabilitiesType
CAP_MAC_OVERRIDE: CapabilitiesType
CAP_MAC_ADMIN: CapabilitiesType
CAP_SYSLOG: CapabilitiesType
CAP_WAKE_ALARM: CapabilitiesType
CAP_BLOCK_SUSPEND: CapabilitiesType
CAP_AUDIT_READ: CapabilitiesType
CAP_PERFMON: CapabilitiesType
CAP_BPF: CapabilitiesType
CAP_CHECKPOINT_RESTORE: CapabilitiesType
SecBitNotSet: SecureBitsType
SecBitNoRoot: SecureBitsType
SecBitNoRootLocked: SecureBitsType
SecBitNoSetUidFixup: SecureBitsType
SecBitNoSetUidFixupLocked: SecureBitsType
SecBitKeepCaps: SecureBitsType
SecBitKeepCapsLocked: SecureBitsType
SecBitNoCapAmbientRaise: SecureBitsType
SecBitNoCapAmbientRaiseLocked: SecureBitsType
